### ISSUE TITLE
Can't install Bridge on Stock Mi A2

### ISSUE THREAD

**Issue by 19Gerhard85** [amirzaidi/AIDLBridge#9]
Hi Amir,

I can't install the Bridge apk on my Stock Mi A2 running Android 9. The default launcher is called "Quickstep" if that helps.

Could be please provide a combined app (Launcher + Bridge) like v2 was?

If you need any further information, let me know.

**Comment by amirzaidi** [comment]
> Could be please provide a combined app (Launcher + Bridge) like v2 was?

This would not fix the issue, you would not be able to install the combined app.
The problem is that the Android 9 update brought Quickstep which has conflicting permissions that are necessary for At A Glance. There is one workaround that Lawnchair is using - they extract the weather from the widget. If I were to add that, I could make it work without the conflicting permission.

For now you can use this Pixel Bridge version without the At A Glance permission:

[Mi A1/A2 Pixel Bridge](https://github.com/amirzaidi/AIDLBridge/files/3217506/mi.a1.a2.pixelbridge.zip)

**Comment by 19Gerhard85** [comment]
Works like a charm, thank you!

**Comment by baryoncascade** [comment]
I can confirm the A1/A2 Bridge does work on my X4 to enable functionality.
